spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/java-bug/protocol/openid-connect/certs

server:
  port : 8081

logging:
  level:
    org:
      keycloak: DEBUG
